name: lit-seq2seq
channels:
  - conda-forge
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch=1.6.0
  - pytorch-lightning
  - tqdm
  - wandb
  - pip:
      - "util@git+https://git@github.com/dertilo/util.git#egg=util"
      - test_tube
